# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "classy_enum"
  s.version = "2.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Brown"]
  s.date = "2012-04-22"
  s.description = "A utility that adds class based enum functionality to ActiveRecord attributes"
  s.email = "github@lette.us"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    ".travis.yml",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "classy_enum.gemspec",
    "gemfiles/Gemfile.rails-3.0.x",
    "gemfiles/Gemfile.rails-3.1.x",
    "gemfiles/Gemfile.rails-3.2.x",
    "init.rb",
    "lib/classy_enum.rb",
    "lib/classy_enum/attributes.rb",
    "lib/classy_enum/base.rb",
    "lib/classy_enum/class_methods.rb",
    "lib/classy_enum/instance_methods.rb",
    "lib/generators/classy_enum/classy_enum_generator.rb",
    "lib/generators/classy_enum/templates/enum.rb",
    "spec/active_record_spec.rb",
    "spec/classy_enum_attributes_spec.rb",
    "spec/classy_enum_owner_reference_spec.rb",
    "spec/classy_enum_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/beerlington/classy_enum"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.19"
  s.summary = "A class based enumerator utility for Ruby on Rails"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 2.8.1"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<json>, ["~> 1.6.5"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rspec-rails>, ["~> 2.8.1"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<json>, ["~> 1.6.5"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rspec-rails>, ["~> 2.8.1"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<json>, ["~> 1.6.5"])
  end
end

